### ISSUE TITLE
Process FOM's application log using a Fluentbit agent and send it to Kinesis

### ISSUE THREAD

**Issue by rparfig** [bcgov/nr-fom#271]
**As a** *Developer* **I want** *to be able to monitor application events* **So That** *I can promptly monitor application issues, categorize and quantify them with the use of Opensearch*

**Additional Context**
- 1Team has successfully implemented monitoring for many on-prem application servers
- The information is extracted from servers with the use of a Fluentbit agent that is installed on the server
- The logs are processed by podman and sent in a JSON format to Kinesis, which then loads it into Opensearch indexes for further analysis
- The events can be then categorized and monitored through alerts configured within Opensearch

**Acceptance Criteria**
- [ ] Through the successful installation of a Fluentbit sidecar for FOM, When an entry is created in the application log, it is ingested by Podman and then sent to Kinesis using the Fluentbit agents.

**Definition of Done**
- [ ] Process to install Fluentbit as a sidecar in Openshift is documented
- [ ] A Fluentbit agent is able to process the FOM's application log 
- [ ] Test for ingesting the log file and creating a JSON output file is successful
- [ ] Fluentbit agent is able to send the JSON file to Kinesis and
- [ ] Opensearch is able to display the events recorded within the application log
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by rparfig** [comment]
Some information provided by Matthew Bystedt to complete this task:

If it is log files then use a fluentbit sidecar to send the logs to kinesis. We'll provide the account to send to kinesis. So, add in something like this: 

```
	volumes:
       ...
        {{- if .Values.fluentbit.enable }}
        - name: fluentbit-config
          secret:
            secretName: {{ template "vault.fullname" . }}-fluentbit
            items:
            - key: fluent-bit.conf
              path: fluent-bit.conf
            - key: fluent-parser.conf
              path: fluent-parser.conf
            defaultMode: 420
     containers:
        - name: fluent-bit
          image: {{ .Values.server.image.prefix }}fluent/fluent-bit:1.8
          env:
              ... setup account env
          volumeMounts:
            - name: audit
              mountPath: /vault/audit
            - name: fluentbit-config
              mountPath: /fluent-bit/etc
```
  
The hardest part is probably the fluentbit configuration. Easiest thing to do is to run the local lambda following the instructions in funbucks. Just put your config in ./output instead of running funbucks to generate one. 

If this is access logs. I recommend using the fingerprint that the broker is using. 

```
event: {
          category: 'web',
          dataset: 'generic.access',
          kind: 'event',
} 
```
